apiVersion: v1
kind: Namespace
metadata:
  name: logging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: logging
---
# RBAC: allow Fluent Bit to enrich logs with Kubernetes metadata
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluent-bit
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit
subjects:
  - kind: ServiceAccount
    name: fluent-bit
    namespace: logging
---
# Output secrets (OpenSearch + S3)
apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-outputs
  namespace: logging
type: Opaque
stringData:
  OPENSEARCH_HOST: "192.168.100.114"
  OPENSEARCH_PORT: "9200"
  OPENSEARCH_USER: "admin"
  OPENSEARCH_PASSWORD: "Pratista17"
  # S3/MinIO (dev)
  S3_ENDPOINT: "http://tabeldata.ip-dynamic.com:39000"
  S3_REGION: "us-east-1"
  S3_BUCKET: "hiteman-log-management"
  S3_ACCESS_KEY: "tabeldata"
  S3_SECRET_KEY: "1eTqbgmJIRdy0ZZKp7fe"
---
# Fluent Bit config
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config-v2
  namespace: logging
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush         1
        Daemon        Off
        Log_Level     info
        Parsers_File  parsers.conf
        HTTP_Server   On
        HTTP_Listen   0.0.0.0
        HTTP_Port     2020

    # Tail only logs coming from the 'sikd' namespace
    [INPUT]
        Name              tail
        Path              /var/log/containers/*_sikd_*.log
        Exclude_Path      /var/log/containers/fluent-bit-*.log
        Tag               kube.*
        Refresh_Interval  5
        Skip_Long_Lines   On
        Mem_Buf_Limit     64MB
        DB                /var/log/fluentbit-sikd.db
        DB.Sync           Normal
        Read_From_Head    Off
        Parser            cri

    # Add Kubernetes metadata
    [FILTER]
        Name                kubernetes
        Match               kube.*
        Kube_URL            https://kubernetes.default.svc:443
        Kube_Tag_Prefix     kube.var.log.containers.
        Merge_Log           On
        Keep_Log            On
        Annotations         Off

    # Keep only logs from namespace=sikd
    [FILTER]
        Name      grep
        Match     kube.*
        Regex     kubernetes.namespace_name  ^sikd$

    # ---------- Output: OpenSearch ----------
    [OUTPUT]
        Name                es
        Match               kube.*
        Host                ${OPENSEARCH_HOST}
        Port                ${OPENSEARCH_PORT}
        HTTP_User           ${OPENSEARCH_USER}
        HTTP_Passwd         ${OPENSEARCH_PASSWORD}
        Logstash_Format     On
        Logstash_Prefix     sikd
        Replace_Dots        On
        Type                _doc
        Time_Key            @timestamp
        Suppress_Type_Name  On
        tls                 On
        tls.verify          Off
        Retry_Limit         False
        Trace_Error         On

    # ---------- Output: S3 (MinIO today, NetApp S3 later) ----------
    # Credentials are provided via env vars: AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY / AWS_REGION
    [OUTPUT]
        Name                  s3
        Match                 kube.*
        bucket                ${S3_BUCKET}
        region                ${S3_REGION}
        endpoint              ${S3_ENDPOINT}      # http://... for MinIO, https://... for NetApp later
        total_file_size       50M
        upload_timeout        2m
        use_put_object        On
        compression           gzip
        s3_key_format         /sikd/%Y/%m/%d/%H/%M/%S-$UUID.gz
        auto_retry_requests   On

  # Parsers (containerd CRI + a simple multiline for Java stack traces)
  parsers.conf: |
    [PARSER]
        Name        cri
        Format      regex
        Regex       ^(?<time>[^ ]+) (?<stream>stdout|stderr) (?<flags>[^ ]*) (?<log>.*)$
        Time_Key    time
        Time_Format %Y-%m-%dT%H:%M:%S.%L%z

    # Optional: Java stacktrace stitching (for Spring Boot), enable by adding 'Multiline.Parser java' in INPUT
    [MULTILINE_PARSER]
        Name          java
        Type          regex
        Flush_Timeout 2000
        Rule          "start_state"   "/^\d{4}-\d{2}-\d{2}T/"  "cont"
        Rule          "cont"          "/^\s+at\s|Caused by:/"  "cont"
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      priorityClassName: system-node-critical
      containers:
        - name: fluent-bit
          image: cr.fluentbit.io/fluent/fluent-bit:2.2.2
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: fluent-bit-outputs
          # Map Secret keys to the AWS_* variables the S3 plugin picks up
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fluent-bit-outputs
                  key: S3_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fluent-bit-outputs
                  key: S3_SECRET_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: fluent-bit-outputs
                  key: S3_REGION
          ports:
            - name: metrics
              containerPort: 2020
              protocol: TCP
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlib
              mountPath: /var/lib
            - name: config
              mountPath: /fluent-bit/etc/
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: varlib
          hostPath:
            path: /var/lib
        - name: config
          configMap:
            name: fluent-bit-config-v2
            items:
              - key: fluent-bit.conf
                path: fluent-bit.conf
              - key: parsers.conf
                path: parsers.conf
