apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-server
  namespace: sikd
  labels:
    app: go-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server
  template:
    metadata:
      name: go-server
      labels:
        app: go-server
    spec:
      containers:
        - name: go-server
          image: docker.io/aprianfirlanda/go-log-producer:0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
      
