apiVersion: v1
kind: Service
metadata:
  name: nodejs-server
  namespace: sikd
  labels:
    app: nodejs-server
spec:
  selector:
    app: nodejs-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
  
